### PR TITLE
Allow default values to be specified

### PR DESCRIPTION
**Pull request by hunner**

### CODE REVIEW

**Comment by hunner** [comment]
I'd like `get()` to raise the 422 when no default is passed and the default anyway, but I don't know of a pythonic way to tell the difference between a default `None` argument value vs. user passing a `None` value in.

**Comment by hunner** [comment]
Tried doing https://stackoverflow.com/a/52500454 and it was ugly and too much magic so never mind.

**Comment by hunner** [comment]
Just closing this. The metadata error responses needs to be formalized before updating SDKs to match.

**Comment by ahpook** [comment]
Just got back to a point where I needed this and realized it got closed but not merged.. I see the concern, but is there really _no_ incremental improvement the SDK can make without a backend change? 😿

**Pull request closed without merging**
